/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import {
  MatchResults,
} from '@stencil/router';

declare global {
  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;
  }
}



import {
  AppFirebase as AppFirebase
} from './components/app-firebase/app-firebase';

declare global {
  interface HTMLAppFirebaseElement extends AppFirebase, HTMLStencilElement {
  }
  var HTMLAppFirebaseElement: {
    prototype: HTMLAppFirebaseElement;
    new (): HTMLAppFirebaseElement;
  };
  interface HTMLElementTagNameMap {
    "app-firebase": HTMLAppFirebaseElement;
  }
  interface ElementTagNameMap {
    "app-firebase": HTMLAppFirebaseElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "app-firebase": JSXElements.AppFirebaseAttributes;
    }
  }
  namespace JSXElements {
    export interface AppFirebaseAttributes extends HTMLAttributes {
      
    }
  }
}


import {
  AppGizmoDetail as AppGizmoDetail
} from './components/app-gizmo-detail/app-gizmo-detail';

declare global {
  interface HTMLAppGizmoDetailElement extends AppGizmoDetail, HTMLStencilElement {
  }
  var HTMLAppGizmoDetailElement: {
    prototype: HTMLAppGizmoDetailElement;
    new (): HTMLAppGizmoDetailElement;
  };
  interface HTMLElementTagNameMap {
    "app-gizmo-detail": HTMLAppGizmoDetailElement;
  }
  interface ElementTagNameMap {
    "app-gizmo-detail": HTMLAppGizmoDetailElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "app-gizmo-detail": JSXElements.AppGizmoDetailAttributes;
    }
  }
  namespace JSXElements {
    export interface AppGizmoDetailAttributes extends HTMLAttributes {
      
    }
  }
}


import {
  AppGizmo as AppGizmo
} from './components/app-gizmo/app-gizmo';

declare global {
  interface HTMLAppGizmoElement extends AppGizmo, HTMLStencilElement {
  }
  var HTMLAppGizmoElement: {
    prototype: HTMLAppGizmoElement;
    new (): HTMLAppGizmoElement;
  };
  interface HTMLElementTagNameMap {
    "app-gizmo": HTMLAppGizmoElement;
  }
  interface ElementTagNameMap {
    "app-gizmo": HTMLAppGizmoElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "app-gizmo": JSXElements.AppGizmoAttributes;
    }
  }
  namespace JSXElements {
    export interface AppGizmoAttributes extends HTMLAttributes {
      
    }
  }
}


import {
  AppHome as AppHome
} from './components/app-home/app-home';

declare global {
  interface HTMLAppHomeElement extends AppHome, HTMLStencilElement {
  }
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };
  interface HTMLElementTagNameMap {
    "app-home": HTMLAppHomeElement;
  }
  interface ElementTagNameMap {
    "app-home": HTMLAppHomeElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "app-home": JSXElements.AppHomeAttributes;
    }
  }
  namespace JSXElements {
    export interface AppHomeAttributes extends HTMLAttributes {
      
    }
  }
}


import {
  AppProfile as AppProfile
} from './components/app-profile/app-profile';

declare global {
  interface HTMLAppProfileElement extends AppProfile, HTMLStencilElement {
  }
  var HTMLAppProfileElement: {
    prototype: HTMLAppProfileElement;
    new (): HTMLAppProfileElement;
  };
  interface HTMLElementTagNameMap {
    "app-profile": HTMLAppProfileElement;
  }
  interface ElementTagNameMap {
    "app-profile": HTMLAppProfileElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "app-profile": JSXElements.AppProfileAttributes;
    }
  }
  namespace JSXElements {
    export interface AppProfileAttributes extends HTMLAttributes {
      match?: MatchResults;
    }
  }
}


import {
  AppSignIn as AppSignIn
} from './components/app-sign-in/app-sign-in';

declare global {
  interface HTMLAppSignInElement extends AppSignIn, HTMLStencilElement {
  }
  var HTMLAppSignInElement: {
    prototype: HTMLAppSignInElement;
    new (): HTMLAppSignInElement;
  };
  interface HTMLElementTagNameMap {
    "app-sign-in": HTMLAppSignInElement;
  }
  interface ElementTagNameMap {
    "app-sign-in": HTMLAppSignInElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "app-sign-in": JSXElements.AppSignInAttributes;
    }
  }
  namespace JSXElements {
    export interface AppSignInAttributes extends HTMLAttributes {
      
    }
  }
}


import {
  LazyImg as LazyImg
} from './components/lazy-img/lazy-img';

declare global {
  interface HTMLLazyImgElement extends LazyImg, HTMLStencilElement {
  }
  var HTMLLazyImgElement: {
    prototype: HTMLLazyImgElement;
    new (): HTMLLazyImgElement;
  };
  interface HTMLElementTagNameMap {
    "lazy-img": HTMLLazyImgElement;
  }
  interface ElementTagNameMap {
    "lazy-img": HTMLLazyImgElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "lazy-img": JSXElements.LazyImgAttributes;
    }
  }
  namespace JSXElements {
    export interface LazyImgAttributes extends HTMLAttributes {
      alt?: string;
      src?: string;
    }
  }
}


import {
  MyApp as MyApp
} from './components/my-app/my-app';

declare global {
  interface HTMLMyAppElement extends MyApp, HTMLStencilElement {
  }
  var HTMLMyAppElement: {
    prototype: HTMLMyAppElement;
    new (): HTMLMyAppElement;
  };
  interface HTMLElementTagNameMap {
    "my-app": HTMLMyAppElement;
  }
  interface ElementTagNameMap {
    "my-app": HTMLMyAppElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "my-app": JSXElements.MyAppAttributes;
    }
  }
  namespace JSXElements {
    export interface MyAppAttributes extends HTMLAttributes {
      
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
