/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}

import 'ionicons';
import '@ionic/core';
import '@stencil/router';

import {
  EventEmitter,
} from '@stencil/core';

declare global {
  interface HTMLAppFirebaseElement extends HTMLStencilElement {

  }
  var HTMLAppFirebaseElement: {
    prototype: HTMLAppFirebaseElement;
    new (): HTMLAppFirebaseElement;
  };
  interface HTMLElementTagNameMap {
    'app-firebase': HTMLAppFirebaseElement;
  }
  interface ElementTagNameMap {
    'app-firebase': HTMLAppFirebaseElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-firebase': JSXElements.AppFirebaseAttributes;
    }
  }
  namespace JSXElements {
    export interface AppFirebaseAttributes extends HTMLAttributes {

    }
  }
}


declare global {
  interface HTMLAppGizmoDetailElement extends HTMLStencilElement {

  }
  var HTMLAppGizmoDetailElement: {
    prototype: HTMLAppGizmoDetailElement;
    new (): HTMLAppGizmoDetailElement;
  };
  interface HTMLElementTagNameMap {
    'app-gizmo-detail': HTMLAppGizmoDetailElement;
  }
  interface ElementTagNameMap {
    'app-gizmo-detail': HTMLAppGizmoDetailElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-gizmo-detail': JSXElements.AppGizmoDetailAttributes;
    }
  }
  namespace JSXElements {
    export interface AppGizmoDetailAttributes extends HTMLAttributes {

    }
  }
}


declare global {
  interface HTMLAppGizmoElement extends HTMLStencilElement {

  }
  var HTMLAppGizmoElement: {
    prototype: HTMLAppGizmoElement;
    new (): HTMLAppGizmoElement;
  };
  interface HTMLElementTagNameMap {
    'app-gizmo': HTMLAppGizmoElement;
  }
  interface ElementTagNameMap {
    'app-gizmo': HTMLAppGizmoElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-gizmo': JSXElements.AppGizmoAttributes;
    }
  }
  namespace JSXElements {
    export interface AppGizmoAttributes extends HTMLAttributes {

    }
  }
}


declare global {
  interface HTMLAppHomeElement extends HTMLStencilElement {

  }
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };
  interface HTMLElementTagNameMap {
    'app-home': HTMLAppHomeElement;
  }
  interface ElementTagNameMap {
    'app-home': HTMLAppHomeElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-home': JSXElements.AppHomeAttributes;
    }
  }
  namespace JSXElements {
    export interface AppHomeAttributes extends HTMLAttributes {

    }
  }
}


declare global {
  interface HTMLAppProfileElement extends HTMLStencilElement {
    'name': string;
  }
  var HTMLAppProfileElement: {
    prototype: HTMLAppProfileElement;
    new (): HTMLAppProfileElement;
  };
  interface HTMLElementTagNameMap {
    'app-profile': HTMLAppProfileElement;
  }
  interface ElementTagNameMap {
    'app-profile': HTMLAppProfileElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-profile': JSXElements.AppProfileAttributes;
    }
  }
  namespace JSXElements {
    export interface AppProfileAttributes extends HTMLAttributes {
      'name'?: string;
    }
  }
}


declare global {
  interface HTMLAppSignInElement extends HTMLStencilElement {

  }
  var HTMLAppSignInElement: {
    prototype: HTMLAppSignInElement;
    new (): HTMLAppSignInElement;
  };
  interface HTMLElementTagNameMap {
    'app-sign-in': HTMLAppSignInElement;
  }
  interface ElementTagNameMap {
    'app-sign-in': HTMLAppSignInElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-sign-in': JSXElements.AppSignInAttributes;
    }
  }
  namespace JSXElements {
    export interface AppSignInAttributes extends HTMLAttributes {

    }
  }
}


declare global {
  interface HTMLLazyImgElement extends HTMLStencilElement {
    'alt': string;
    'src': string;
  }
  var HTMLLazyImgElement: {
    prototype: HTMLLazyImgElement;
    new (): HTMLLazyImgElement;
  };
  interface HTMLElementTagNameMap {
    'lazy-img': HTMLLazyImgElement;
  }
  interface ElementTagNameMap {
    'lazy-img': HTMLLazyImgElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'lazy-img': JSXElements.LazyImgAttributes;
    }
  }
  namespace JSXElements {
    export interface LazyImgAttributes extends HTMLAttributes {
      'alt'?: string;
      'onLazyImgloaded'?: (event: CustomEvent<HTMLImageElement>) => void;
      'src'?: string;
    }
  }
}


declare global {
  interface HTMLMyAppElement extends HTMLStencilElement {

  }
  var HTMLMyAppElement: {
    prototype: HTMLMyAppElement;
    new (): HTMLMyAppElement;
  };
  interface HTMLElementTagNameMap {
    'my-app': HTMLMyAppElement;
  }
  interface ElementTagNameMap {
    'my-app': HTMLMyAppElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'my-app': JSXElements.MyAppAttributes;
    }
  }
  namespace JSXElements {
    export interface MyAppAttributes extends HTMLAttributes {

    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
